#!/usr/bin/env bash

URL="http://13.53.146.18/data"

if [[ ${USER} == "root" ]]; then
   echo "NEVER RUN THIS SCRIPT AS ROOT!"
   exit 1
elif [[${USER} != "admin" ]]; then
   echo "Please run this script as admin"
   exit 2
else
   echo "Validation passed"
fi

if [[ -z ${1} ]]; then
   backup_dir="${HOME}/app/data"
else
   backup_dir="${HOME}/app/${1}"
fi

mkdir -p ${backup_dir}
cd ${backup_dir}

echod () {
 d="$(date +"%Y-%m-%d %H:%M:%S")"
 echo "${d} ${1}"
}

files=$(curl -s -L ${URL} | grep -o -E "href=\"[[:alnum:]].*\"" | cut -d '=' -f 2 | tr -d '"')
for file in ${files}; do
   (
   echod "Downloading ${file} data file"
   curl -s -L -o ${file} ${URL}/${file}
   if [[ $? -ne 0 ]]; then
        echod "Download ${file} failed"
        exit 3
   fi
   sleep 0.1
   echod "Download complete"
   )&
done

for sha_file in $(ls *sha256); do
  sha256sum -c ${sha_file}
done

wait
echod "Job is done"
