version: '3'
services:
  wordpress:
    image: wordpress
    ports:
      - 8081:80
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=wpuser
      - WORDPRESS_DB_PASSWORD=12345
      - WORDPRESS_DB_NAME=wpdb
    volumes:
      - "./wp-data:/var/www/html"
    links:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=wpdb
      - MYSQL_USER=wpuser
      - MYSQL_PASSWORD=12345
    volumes:
      - "./mysql-data:/var/lib/mysql"
